In [2]:
# 导入包
import torch
import numpy as np

# 1、数据类型
    int                     IntTensor
    float                   FloatTensor
    int array               IntTensor[d1,d2,...]
    float array             FloatTensor[d1,d2,...]
    string                  使用编码的方式表示string类型

# from_numpy()
使用 from_numpy() 将 numpy 数据转化为 tensor    
默认为torch.float64类型 torch.DoubleTensor

In [3]:
# import from numpy
a = np.array([2,3.4])
a = torch.from_numpy(a)
print(a)
b = np.ones([2,3])
b = torch.from_numpy(b)
print(b)

tensor([2.0000, 3.4000], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [4]:
# import from list
a = torch.tensor([2., 3.2])
print(a, a.type())
b = torch.tensor([[2,3.2], [1,2.2]])
print(b, b.type())

tensor([2.0000, 3.2000]) torch.FloatTensor
tensor([[2.0000, 3.2000],
        [1.0000, 2.2000]]) torch.FloatTensor


# empty, Tensor, IntTensor, FloatTensor的应用
torch.Tensor()是python类-----------torch.FloatTensor    
torch.tensor()是python函数  
Tensor()接收维度， tensor()接收数据     
效果差不多，用法有一定的区别

In [5]:
# 初始化数据的函数
a = torch.empty(1,4)
print(a, a.type()) 
b = torch.Tensor(2,3)   # 随机
print(b, b.type())
c = torch.tensor((1,2,3))
print(c, c.type())

tensor([[2.0000, 3.2000, 1.0000, 2.2000]]) torch.FloatTensor
tensor([[1.4013e-45, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]]) torch.FloatTensor
tensor([1, 2, 3]) torch.LongTensor


# 改变默认数据类型 
PyTorch的默认类型是FloatTensor  
使用set_default_tensor_type()改变默认数据类型

In [6]:
print(torch.tensor([1.2, 3]).type())
torch.set_default_tensor_type(torch.DoubleTensor)
print(torch.tensor([1.2, 3]).type())

torch.FloatTensor
torch.DoubleTensor


# 切片

In [7]:
a = torch.rand(4,5,6)
print(a.shape)
b = a[0:3:2,:,:]
print(b.shape)
print(a[a>0.5])

torch.Size([4, 5, 6])
torch.Size([2, 5, 6])
tensor([0.6936, 0.9394, 0.9397, 0.9787, 0.9150, 0.8667, 0.5601, 0.9153, 0.7309,
        0.9306, 0.6538, 0.9322, 0.8870, 0.5531, 0.7974, 0.7186, 0.8980, 0.9557,
        0.9117, 0.8556, 0.9401, 0.5395, 0.8598, 0.7060, 0.9280, 0.5256, 0.5206,
        0.5533, 0.5410, 0.9701, 0.6932, 0.5313, 0.9273, 0.8299, 0.5970, 0.6014,
        0.7863, 0.9361, 0.9103, 0.6167, 0.8537, 0.8245, 0.9504, 0.6056, 0.7900,
        0.9390, 0.5073, 0.7526, 0.9440, 0.8614, 0.5380, 0.5162, 0.5357, 0.7737,
        0.6298, 0.7770, 0.6930, 0.9038, 0.9779, 0.5127, 0.8271, 0.5641, 0.5185,
        0.9992, 0.6761])


# 维度变换

In [8]:
# 使用view变换维度
a = torch.rand(4,3,2)
print(a)

b = a.view(4, 3*2)
print(b)

tensor([[[0.2455, 0.2880],
         [0.2440, 0.8290],
         [0.1475, 0.2931]],

        [[0.9267, 0.8703],
         [0.6951, 0.8969],
         [0.9060, 0.5716]],

        [[0.9045, 0.0141],
         [0.0079, 0.7683],
         [0.2523, 0.5554]],

        [[0.9802, 0.7401],
         [0.8259, 0.2694],
         [0.5085, 0.3293]]])
tensor([[0.2455, 0.2880, 0.2440, 0.8290, 0.1475, 0.2931],
        [0.9267, 0.8703, 0.6951, 0.8969, 0.9060, 0.5716],
        [0.9045, 0.0141, 0.0079, 0.7683, 0.2523, 0.5554],
        [0.9802, 0.7401, 0.8259, 0.2694, 0.5085, 0.3293]])


In [9]:
# 使用 unsqueeze 增维
# unsqueeze(x) 再x位置上插入一个维度
print(a.unsqueeze(0).shape)
print(a.unsqueeze(1).shape)
print(a.unsqueeze(-1).shape)
print(a.unsqueeze(-2).shape)

torch.Size([1, 4, 3, 2])
torch.Size([4, 1, 3, 2])
torch.Size([4, 3, 2, 1])
torch.Size([4, 3, 1, 2])


In [10]:
# 使用 unsqueeze 降维(不包含参数的维度)
a = torch.rand(4,3,1,1)
print(a.squeeze(0).shape)
print(a.squeeze(1).shape)
print(a.squeeze(2).shape)
print(a.squeeze(3).shape)
print(a.squeeze(2).squeeze(2).shape)


torch.Size([4, 3, 1, 1])
torch.Size([4, 3, 1, 1])
torch.Size([4, 3, 1])
torch.Size([4, 3, 1])
torch.Size([4, 3])


In [11]:
# 使用 expand 扩展维度(扩张维度为1的位置)
a = torch.rand(4,2,1)
print(a)
print(a.expand(4,2,2))

tensor([[[0.7489],
         [0.4490]],

        [[0.6514],
         [0.5683]],

        [[0.1570],
         [0.5956]],

        [[0.6240],
         [0.0187]]])
tensor([[[0.7489, 0.7489],
         [0.4490, 0.4490]],

        [[0.6514, 0.6514],
         [0.5683, 0.5683]],

        [[0.1570, 0.1570],
         [0.5956, 0.5956]],

        [[0.6240, 0.6240],
         [0.0187, 0.0187]]])


In [12]:
# 使用 repeat 扩展维度
a = torch.rand(2,1)
print(a)
print(a.repeat(2,2))
print(a.repeat(2*2,2))

tensor([[0.0964],
        [0.7904]])
tensor([[0.0964, 0.0964],
        [0.7904, 0.7904],
        [0.0964, 0.0964],
        [0.7904, 0.7904]])
tensor([[0.0964, 0.0964],
        [0.7904, 0.7904],
        [0.0964, 0.0964],
        [0.7904, 0.7904],
        [0.0964, 0.0964],
        [0.7904, 0.7904],
        [0.0964, 0.0964],
        [0.7904, 0.7904]])


# 拼接与拆分 --- Cat, Stack, Split, Chunk

In [13]:
a = torch.rand(2,2)
b = torch.rand(2,2)
print(a, b)
print(torch.cat([a, b], dim=1).shape)
print(torch.cat([a, b], dim=0).shape)
print(torch.stack([a, b], dim=0).shape)
print(torch.stack([a, b], dim=1).shape)
print(a.split(1, dim=1))
print(a.chunk(2, dim=0))    # 等量分割

tensor([[0.9188, 0.3542],
        [0.5319, 0.3193]]) tensor([[0.9521, 0.8719],
        [0.5709, 0.3198]])
torch.Size([2, 4])
torch.Size([4, 2])
torch.Size([2, 2, 2])
torch.Size([2, 2, 2])
(tensor([[0.9188],
        [0.5319]]), tensor([[0.3542],
        [0.3193]]))
(tensor([[0.9188, 0.3542]]), tensor([[0.5319, 0.3193]]))


# PyTorch 的基本数学运算
## 数学运算
Add/minus/multiply/divide   
Matmul  
Pow     
Sqrt/rsqrt  
Round


In [14]:
# add 加
a = torch.rand(3,4)
b = torch.rand(4)
print(a, "\n", b)
print(a+b)
print(torch.add(a,b))

tensor([[0.2994, 0.2528, 0.8189, 0.1437],
        [0.2561, 0.6133, 0.6274, 0.5532],
        [0.0713, 0.0568, 0.1305, 0.3492]]) 
 tensor([0.2602, 0.2979, 0.0097, 0.1281])
tensor([[0.5596, 0.5507, 0.8286, 0.2717],
        [0.5163, 0.9112, 0.6371, 0.6813],
        [0.3314, 0.3547, 0.1402, 0.4773]])
tensor([[0.5596, 0.5507, 0.8286, 0.2717],
        [0.5163, 0.9112, 0.6371, 0.6813],
        [0.3314, 0.3547, 0.1402, 0.4773]])


In [15]:
# sub 减；mul 乘；div 除
print(torch.sub(a,b))
print(torch.mul(a,b))
print(torch.div(a,b))


tensor([[ 0.0392, -0.0451,  0.8092,  0.0156],
        [-0.0041,  0.3154,  0.6177,  0.4251],
        [-0.1889, -0.2411,  0.1208,  0.2211]])
tensor([[0.0779, 0.0753, 0.0079, 0.0184],
        [0.0666, 0.1827, 0.0061, 0.0709],
        [0.0185, 0.0169, 0.0013, 0.0447]])
tensor([[ 1.1505,  0.8486, 84.3602,  1.1217],
        [ 0.9844,  2.0586, 64.6309,  4.3194],
        [ 0.2738,  0.1906, 13.4455,  2.7264]])


In [16]:
torch.eq(a-b, torch.sub(a,b))
torch.all(torch.eq(a-b, torch.sub(a,b)))

tensor(True)

In [17]:
# 矩阵相乘 matmul --- 另一种写法：@
a = torch.rand(1,4)
b = torch.rand(4,1)
print(torch.matmul(a,b))
print(a@b)


tensor([[1.0767]])
tensor([[1.0767]])


In [18]:
# Power exp log
# sqrt ,rsqrt
a = torch.full([2,3],3)
print(a.pow(2))
print(a**2)

tensor([[9, 9, 9],
        [9, 9, 9]])
tensor([[9, 9, 9],
        [9, 9, 9]])


# 统计性质
norm----范数        
mean_sum    
prod----所有元素的积    
max, min, argmin, argmax    
kthvalue, topk

In [19]:
a = torch.arange(8).view(2,4).type(torch.FloatTensor)
print(a)
print(a.min(), a.max(), a.mean(), a.prod())

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]], dtype=torch.float32)
tensor(0., dtype=torch.float32) tensor(7., dtype=torch.float32) tensor(3.5000, dtype=torch.float32) tensor(0., dtype=torch.float32)


In [32]:
# 类中__call__的使用
class test:
    def __init__(self, a):
        print(a)
        pass
    def __call__(self, b):
        print(b)
        pass
c = test(1111)

c(111111111)

1111
111111111


# where 和 gather操作

In [21]:
# where
# torch.where(condition, x, y)
cond = torch.rand(2,2)
print(cond)
a = torch.ones(2,2)
b = torch.zeros(2,2)
torch.where(cond>0.5, a, b)

tensor([[0.2367, 0.7066],
        [0.9486, 0.6572]])


tensor([[0., 1.],
        [1., 1.]])

In [22]:
# gather搜集
# torch.gather(input, dim, index, out=None)
a = torch.arange(10)+100
print(a)
torch.gather(a.expand(4,10), dim=1, index=torch.tensor([[1,1,2],[1,2,3],[1,4,3],[0,5,3]]))

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])


tensor([[101, 101, 102],
        [101, 102, 103],
        [101, 104, 103],
        [100, 105, 103]])

# PyTorch 自动求导
1、创建求导变量，在创建张量时 requires_grad=True    
2、使用 backward() 求出导数（梯度）或者使用 autograd.grad() 求出导数（梯度）

In [23]:
from torch.nn import functional as F
x = torch.ones(1)
# w = torch.full([1],5., requires_grad=True)
w = torch.full([1],5.)
w.requires_grad_()
mse = F.mse_loss(torch.ones(1), x*w)

# 使用 autograd.grad() 求导
# 使用 retain_graph 可保留图（每次求导，图被清除，必须再次建立，使用retain_graph可保留图到下次求导）
a = torch.autograd.grad(mse, [w], retain_graph=True)
print(a)

# 使用 backward() 求导
mse.backward()
print(w.grad)


(tensor([8.]),)
tensor([8.])


In [45]:
a=torch.tensor([-1,2,3])
b=torch.tensor([3,2,3])
a[1] = 11
print(a)
torch.where((a>1)&(b<3))

torch.abs(a)

tensor([-1, 11,  3])


tensor([ 1, 11,  3])