In [2]:
# 导入包
import torch
import numpy as np

# 1、数据类型
    int                     IntTensor
    float                   FloatTensor
    int array               IntTensor[d1,d2,...]
    float array             FloatTensor[d1,d2,...]
    string                  使用编码的方式表示string类型

# from_numpy()
使用 from_numpy() 将 numpy 数据转化为 tensor    
默认为torch.float64类型 torch.DoubleTensor

In [3]:
# import from numpy
a = np.array([2,3.4])
a = torch.from_numpy(a)
print(a)
b = np.ones([2,3])
b = torch.from_numpy(b)
print(b)

tensor([2.0000, 3.4000], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [4]:
# import from list
a = torch.tensor([2., 3.2])
print(a, a.type())
b = torch.tensor([[2,3.2], [1,2.2]])
print(b, b.type())

tensor([2.0000, 3.2000]) torch.FloatTensor
tensor([[2.0000, 3.2000],
        [1.0000, 2.2000]]) torch.FloatTensor


# empty, Tensor, IntTensor, FloatTensor的应用
torch.Tensor()是python类-----------torch.FloatTensor    
torch.tensor()是python函数  
Tensor()接收维度， tensor()接收数据     
效果差不多，用法有一定的区别

In [5]:
# 初始化数据的函数
a = torch.empty(1,4)
print(a, a.type()) 
b = torch.Tensor(2,3)   # 随机
print(b, b.type())
c = torch.tensor((1,2,3))
print(c, c.type())

tensor([[4.2698e-08, 8.3092e+20, 7.9869e+20, 1.0140e-11]]) torch.FloatTensor
tensor([[-2.2105e-30,  7.2587e-43,  3.0357e+32],
        [ 1.1547e+19,  0.0000e+00,  0.0000e+00]]) torch.FloatTensor
tensor([1, 2, 3]) torch.LongTensor


# 改变默认数据类型 
PyTorch的默认类型是FloatTensor  
使用set_default_tensor_type()改变默认数据类型

In [6]:
print(torch.tensor([1.2, 3]).type())
torch.set_default_tensor_type(torch.DoubleTensor)
print(torch.tensor([1.2, 3]).type())

torch.FloatTensor
torch.DoubleTensor


# 切片

In [7]:
a = torch.rand(4,5,6)
print(a.shape)
b = a[0:3:2,:,:]
print(b.shape)
print(a[a>0.5])

torch.Size([4, 5, 6])
torch.Size([2, 5, 6])
tensor([0.7543, 0.8515, 0.8316, 0.5435, 0.6555, 0.9142, 0.9399, 0.6452, 0.9910,
        0.5366, 0.9647, 0.6879, 0.8466, 0.6798, 0.8549, 0.9124, 0.6752, 0.9902,
        0.7548, 0.8577, 0.5822, 0.6872, 0.8850, 0.9262, 0.7082, 0.6599, 0.8990,
        0.7745, 0.5887, 0.9983, 0.8170, 0.7263, 0.5289, 0.5518, 0.9085, 0.6054,
        0.7964, 0.7283, 0.9396, 0.9081, 0.8416, 0.8284, 0.8562, 0.8836, 0.7603,
        0.5921, 0.5959, 0.9470, 0.8783, 0.8754, 0.5858, 0.8404, 0.8956, 0.5379,
        0.9475, 0.8345, 0.7375, 0.8195, 0.7485, 0.8642, 0.9588, 0.7558, 0.5102,
        0.5472])


# 维度变换

In [8]:
# 使用view变换维度
a = torch.rand(4,3,2)
print(a)

b = a.view(4, 3*2)
print(b)

tensor([[[0.7726, 0.0685],
         [0.6279, 0.9718],
         [0.4022, 0.2028]],

        [[0.1264, 0.9693],
         [0.4769, 0.5182],
         [0.1508, 0.2620]],

        [[0.9372, 0.7418],
         [0.7445, 0.1386],
         [0.4335, 0.2610]],

        [[0.2707, 0.8243],
         [0.3965, 0.6164],
         [0.6898, 0.4396]]])
tensor([[0.7726, 0.0685, 0.6279, 0.9718, 0.4022, 0.2028],
        [0.1264, 0.9693, 0.4769, 0.5182, 0.1508, 0.2620],
        [0.9372, 0.7418, 0.7445, 0.1386, 0.4335, 0.2610],
        [0.2707, 0.8243, 0.3965, 0.6164, 0.6898, 0.4396]])


In [9]:
# 使用 unsqueeze 增维
# unsqueeze(x) 再x位置上插入一个维度
print(a.unsqueeze(0).shape)
print(a.unsqueeze(1).shape)
print(a.unsqueeze(-1).shape)
print(a.unsqueeze(-2).shape)

torch.Size([1, 4, 3, 2])
torch.Size([4, 1, 3, 2])
torch.Size([4, 3, 2, 1])
torch.Size([4, 3, 1, 2])


In [10]:
# 使用 unsqueeze 降维(不包含参数的维度)
a = torch.rand(4,3,1,1)
print(a.squeeze(0).shape)
print(a.squeeze(1).shape)
print(a.squeeze(2).shape)
print(a.squeeze(3).shape)
print(a.squeeze(2).squeeze(2).shape)


torch.Size([4, 3, 1, 1])
torch.Size([4, 3, 1, 1])
torch.Size([4, 3, 1])
torch.Size([4, 3, 1])
torch.Size([4, 3])


In [11]:
# 使用 expand 扩展维度(扩张维度为1的位置)
a = torch.rand(4,2,1)
print(a)
print(a.expand(4,2,2))

tensor([[[0.3847],
         [0.3039]],

        [[0.6784],
         [0.0785]],

        [[0.8853],
         [0.6554]],

        [[0.2758],
         [0.3632]]])
tensor([[[0.3847, 0.3847],
         [0.3039, 0.3039]],

        [[0.6784, 0.6784],
         [0.0785, 0.0785]],

        [[0.8853, 0.8853],
         [0.6554, 0.6554]],

        [[0.2758, 0.2758],
         [0.3632, 0.3632]]])


In [12]:
# 使用 repeat 扩展维度
a = torch.rand(2,1)
print(a)
print(a.repeat(2,2))
print(a.repeat(2*2,2))

tensor([[0.0200],
        [0.9709]])
tensor([[0.0200, 0.0200],
        [0.9709, 0.9709],
        [0.0200, 0.0200],
        [0.9709, 0.9709]])
tensor([[0.0200, 0.0200],
        [0.9709, 0.9709],
        [0.0200, 0.0200],
        [0.9709, 0.9709],
        [0.0200, 0.0200],
        [0.9709, 0.9709],
        [0.0200, 0.0200],
        [0.9709, 0.9709]])


# 拼接与拆分 --- Cat, Stack, Split, Chunk

In [13]:
a = torch.rand(2,2)
b = torch.rand(2,2)
print(a, b)
print(torch.cat([a, b], dim=1).shape)
print(torch.cat([a, b], dim=0).shape)
print(torch.stack([a, b], dim=0).shape)
print(torch.stack([a, b], dim=1).shape)
print(a.split(1, dim=1))
print(a.chunk(2, dim=0))    # 等量分割

tensor([[0.6166, 0.0720],
        [0.2380, 0.9987]]) tensor([[0.2861, 0.6472],
        [0.2731, 0.1434]])
torch.Size([2, 4])
torch.Size([4, 2])
torch.Size([2, 2, 2])
torch.Size([2, 2, 2])
(tensor([[0.6166],
        [0.2380]]), tensor([[0.0720],
        [0.9987]]))
(tensor([[0.6166, 0.0720]]), tensor([[0.2380, 0.9987]]))


# PyTorch 的基本数学运算
## 数学运算
Add/minus/multiply/divide   
Matmul  
Pow     
Sqrt/rsqrt  
Round


In [14]:
# add 加
a = torch.rand(3,4)
b = torch.rand(4)
print(a, "\n", b)
print(a+b)
print(torch.add(a,b))

tensor([[0.3936, 0.8021, 0.0992, 0.4079],
        [0.2735, 0.9221, 0.4205, 0.7846],
        [0.4725, 0.3185, 0.5587, 0.2171]]) 
 tensor([0.1174, 0.7374, 0.5564, 0.7846])
tensor([[0.5110, 1.5394, 0.6556, 1.1925],
        [0.3908, 1.6595, 0.9769, 1.5692],
        [0.5899, 1.0558, 1.1151, 1.0017]])
tensor([[0.5110, 1.5394, 0.6556, 1.1925],
        [0.3908, 1.6595, 0.9769, 1.5692],
        [0.5899, 1.0558, 1.1151, 1.0017]])


In [15]:
# sub 减；mul 乘；div 除
print(torch.sub(a,b))
print(torch.mul(a,b))
print(torch.div(a,b))


tensor([[ 2.7626e-01,  6.4664e-02, -4.5720e-01, -3.7673e-01],
        [ 1.5612e-01,  1.8473e-01, -1.3585e-01,  1.3764e-05],
        [ 3.5514e-01, -4.1893e-01,  2.2625e-03, -5.6746e-01]])
tensor([[0.0462, 0.5914, 0.0552, 0.3200],
        [0.0321, 0.6800, 0.2340, 0.6156],
        [0.0555, 0.2348, 0.3108, 0.1704]])
tensor([[3.3540, 1.0877, 0.1783, 0.5198],
        [2.3303, 1.2505, 0.7558, 1.0000],
        [4.0262, 0.4319, 1.0041, 0.2768]])


In [16]:
torch.eq(a-b, torch.sub(a,b))
torch.all(torch.eq(a-b, torch.sub(a,b)))

tensor(True)

In [17]:
# 矩阵相乘 matmul --- 另一种写法：@
a = torch.rand(1,4)
b = torch.rand(4,1)
print(torch.matmul(a,b))
print(a@b)


tensor([[1.1517]])
tensor([[1.1517]])


In [18]:
# Power exp log
# sqrt ,rsqrt
a = torch.full([2,3],3)
print(a.pow(2))
print(a**2)

tensor([[9, 9, 9],
        [9, 9, 9]])
tensor([[9, 9, 9],
        [9, 9, 9]])


# 统计性质
norm----范数        
mean_sum    
prod----所有元素的积    
max, min, argmin, argmax    
kthvalue, topk

In [29]:
a = torch.arange(8).view(2,4).type(torch.FloatTensor)
print(a)
print(a.min(), a.max(), a.mean(), a.prod())

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]], dtype=torch.float32)
tensor(0., dtype=torch.float32) tensor(7., dtype=torch.float32) tensor(3.5000, dtype=torch.float32) tensor(0., dtype=torch.float32)


In [34]:
# 类中__call__的使用
class test():
    def __init__(self, a):
        print(a)
        pass
    def __call__(self, b):
        print(b)
        pass
c = test(1111)
c(111111111)

1111
111111111


# where 和 gather操作

In [39]:
# where
# torch.where(condition, x, y)
cond = torch.rand(2,2)
print(cond)
a = torch.ones(2,2)
b = torch.zeros(2,2)
torch.where(cond>0.5, a, b)

tensor([[0.2764, 0.6698],
        [0.5015, 0.1711]])


tensor([[0., 1.],
        [1., 0.]])

In [45]:
# gather搜集
# torch.gather(input, dim, index, out=None)
a = torch.arange(10)+100
print(a)
torch.gather(a.expand(4,10), dim=1, index=torch.tensor([[1,1,2],[1,2,3],[1,4,3],[0,5,3]]))

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])


tensor([[101, 101, 102],
        [101, 102, 103],
        [101, 104, 103],
        [100, 105, 103]])