In [2]:
# 导入包
import torch
import numpy as np

# 1、数据类型
    int                     IntTensor
    float                   FloatTensor
    int array               IntTensor[d1,d2,...]
    float array             FloatTensor[d1,d2,...]
    string                  使用编码的方式表示string类型

# from_numpy()
使用 from_numpy() 将 numpy 数据转化为 tensor    
默认为torch.float64类型 torch.DoubleTensor

In [8]:
# import from numpy
a = np.array([2,3.4])
a = torch.from_numpy(a)
print(a)
b = np.ones([2,3])
b = torch.from_numpy(b)
print(b)

tensor([2.0000, 3.4000], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [15]:
# import from list
a = torch.tensor([2., 3.2])
print(a, a.type())
b = torch.tensor([[2,3.2], [1,2.2]])
print(b, b.type())

tensor([2.0000, 3.2000]) torch.FloatTensor
tensor([[2.0000, 3.2000],
        [1.0000, 2.2000]]) torch.FloatTensor


# empty, Tensor, IntTensor, FloatTensor的应用
torch.Tensor()是python类-----------torch.FloatTensor    
torch.tensor()是python函数  
Tensor()接收维度， tensor()接收数据     
效果差不多，用法有一定的区别

In [26]:
# 初始化数据的函数
a = torch.empty(1,4)
print(a, a.type()) 
b = torch.Tensor(2,3)   # 随机
print(b, b.type())
c = torch.tensor((1,2,3))
print(c, c.type())

tensor([[0., 0., 0., 0.]]) torch.FloatTensor
tensor([[0.0000e+00, 3.2485e-05, 1.8754e+28],
        [2.5991e-06, 2.6542e+20, 1.2801e-11]]) torch.FloatTensor
tensor([1, 2, 3]) torch.LongTensor


In [31]:
b.reshape(1,6)

tensor([[0.0000e+00, 3.2485e-05, 1.8754e+28, 2.5991e-06, 2.6542e+20, 1.2801e-11]])