In [2]:
# 导入包
import torch
import numpy as np

# 1、数据类型
    int                     IntTensor
    float                   FloatTensor
    int array               IntTensor[d1,d2,...]
    float array             FloatTensor[d1,d2,...]
    string                  使用编码的方式表示string类型

# from_numpy()
使用 from_numpy() 将 numpy 数据转化为 tensor    
默认为torch.float64类型 torch.DoubleTensor

In [3]:
# import from numpy
a = np.array([2,3.4])
a = torch.from_numpy(a)
print(a)
b = np.ones([2,3])
b = torch.from_numpy(b)
print(b)

tensor([2.0000, 3.4000], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [4]:
# import from list
a = torch.tensor([2., 3.2])
print(a, a.type())
b = torch.tensor([[2,3.2], [1,2.2]])
print(b, b.type())

tensor([2.0000, 3.2000]) torch.FloatTensor
tensor([[2.0000, 3.2000],
        [1.0000, 2.2000]]) torch.FloatTensor


# empty, Tensor, IntTensor, FloatTensor的应用
torch.Tensor()是python类-----------torch.FloatTensor    
torch.tensor()是python函数  
Tensor()接收维度， tensor()接收数据     
效果差不多，用法有一定的区别

In [5]:
# 初始化数据的函数
a = torch.empty(1,4)
print(a, a.type()) 
b = torch.Tensor(2,3)   # 随机
print(b, b.type())
c = torch.tensor((1,2,3))
print(c, c.type())

tensor([[ 0.0000e+00,         nan, -7.0128e+11,  8.9543e-43]]) torch.FloatTensor
tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 8.9543e-43]]) torch.FloatTensor
tensor([1, 2, 3]) torch.LongTensor


# 改变默认数据类型 
PyTorch的默认类型是FloatTensor  
使用set_default_tensor_type()改变默认数据类型

In [6]:
print(torch.tensor([1.2, 3]).type())
torch.set_default_tensor_type(torch.DoubleTensor)
print(torch.tensor([1.2, 3]).type())

torch.FloatTensor
torch.DoubleTensor


# 切片

In [7]:
a = torch.rand(4,5,6)
print(a.shape)
b = a[0:3:2,:,:]
print(b.shape)
print(a[a>0.5])

torch.Size([4, 5, 6])
torch.Size([2, 5, 6])
tensor([0.5367, 0.6427, 0.6292, 0.8174, 0.7703, 0.9470, 0.5937, 0.6342, 0.6710,
        0.8164, 0.5957, 0.7833, 0.5554, 0.5252, 0.8230, 0.6194, 0.7529, 0.9362,
        0.8237, 0.8761, 0.9560, 0.6542, 0.6946, 0.8084, 0.6256, 0.7092, 0.9195,
        0.9538, 0.8504, 0.9426, 0.8878, 0.6145, 0.7628, 0.9353, 0.6431, 0.5185,
        0.5811, 0.6726, 0.9313, 0.9609, 0.9218, 0.9146, 0.9001, 0.8053, 0.8924,
        0.8533, 0.8756, 0.9888, 0.7353, 0.9842, 0.5370, 0.7046, 0.5139, 0.9883,
        0.8992, 0.6856, 0.6633, 0.8428, 0.9896, 0.5692, 0.9610, 0.9237, 0.7623,
        0.8798, 0.6895, 0.6518])


# 维度变换

In [8]:
# 使用view变换维度
a = torch.rand(4,3,2)
print(a)

b = a.view(4, 3*2)
print(b)

tensor([[[0.8063, 0.1488],
         [0.3338, 0.7083],
         [0.4969, 0.2100]],

        [[0.5345, 0.0873],
         [0.2173, 0.2530],
         [0.6445, 0.3866]],

        [[0.8425, 0.2169],
         [0.7613, 0.6000],
         [0.9416, 0.1514]],

        [[0.8783, 0.2111],
         [0.6348, 0.1420],
         [0.7341, 0.1306]]])
tensor([[0.8063, 0.1488, 0.3338, 0.7083, 0.4969, 0.2100],
        [0.5345, 0.0873, 0.2173, 0.2530, 0.6445, 0.3866],
        [0.8425, 0.2169, 0.7613, 0.6000, 0.9416, 0.1514],
        [0.8783, 0.2111, 0.6348, 0.1420, 0.7341, 0.1306]])


In [9]:
# 使用 unsqueeze 增维
# unsqueeze(x) 再x位置上插入一个维度
print(a.unsqueeze(0).shape)
print(a.unsqueeze(1).shape)
print(a.unsqueeze(-1).shape)
print(a.unsqueeze(-2).shape)

torch.Size([1, 4, 3, 2])
torch.Size([4, 1, 3, 2])
torch.Size([4, 3, 2, 1])
torch.Size([4, 3, 1, 2])


In [10]:
# 使用 unsqueeze 降维(不包含参数的维度)
a = torch.rand(4,3,1,1)
print(a.squeeze(0).shape)
print(a.squeeze(1).shape)
print(a.squeeze(2).shape)
print(a.squeeze(3).shape)
print(a.squeeze(2).squeeze(2).shape)


torch.Size([4, 3, 1, 1])
torch.Size([4, 3, 1, 1])
torch.Size([4, 3, 1])
torch.Size([4, 3, 1])
torch.Size([4, 3])


In [11]:
# 使用 expand 扩展维度(扩张维度为1的位置)
a = torch.rand(4,2,1)
print(a)
print(a.expand(4,2,2))

tensor([[[0.4329],
         [0.3081]],

        [[0.9665],
         [0.1837]],

        [[0.4874],
         [0.0620]],

        [[0.8363],
         [0.7169]]])
tensor([[[0.4329, 0.4329],
         [0.3081, 0.3081]],

        [[0.9665, 0.9665],
         [0.1837, 0.1837]],

        [[0.4874, 0.4874],
         [0.0620, 0.0620]],

        [[0.8363, 0.8363],
         [0.7169, 0.7169]]])


In [12]:
# 使用 repeat 扩展维度
a = torch.rand(2,1)
print(a)
print(a.repeat(2,2))
print(a.repeat(2*2,2))

tensor([[0.8846],
        [0.2506]])
tensor([[0.8846, 0.8846],
        [0.2506, 0.2506],
        [0.8846, 0.8846],
        [0.2506, 0.2506]])
tensor([[0.8846, 0.8846],
        [0.2506, 0.2506],
        [0.8846, 0.8846],
        [0.2506, 0.2506],
        [0.8846, 0.8846],
        [0.2506, 0.2506],
        [0.8846, 0.8846],
        [0.2506, 0.2506]])


# 拼接与拆分 --- Cat, Stack, Split, Chunk

In [13]:
a = torch.rand(2,2)
b = torch.rand(2,2)
print(a, b)
print(torch.cat([a, b], dim=1).shape)
print(torch.cat([a, b], dim=0).shape)
print(torch.stack([a, b], dim=0).shape)
print(torch.stack([a, b], dim=1).shape)
print(a.split(1, dim=1))
print(a.chunk(2, dim=0))    # 等量分割

tensor([[0.9559, 0.8819],
        [0.0077, 0.8526]]) tensor([[0.0281, 0.2573],
        [0.1914, 0.9745]])
torch.Size([2, 4])
torch.Size([4, 2])
torch.Size([2, 2, 2])
torch.Size([2, 2, 2])
(tensor([[0.9559],
        [0.0077]]), tensor([[0.8819],
        [0.8526]]))
(tensor([[0.9559, 0.8819]]), tensor([[0.0077, 0.8526]]))


# PyTorch 的基本数学运算
## 数学运算
Add/minus/multiply/divide   
Matmul  
Pow     
Sqrt/rsqrt  
Round


In [14]:
# add 加
a = torch.rand(3,4)
b = torch.rand(4)
print(a, "\n", b)
print(a+b)
print(torch.add(a,b))

tensor([[0.7376, 0.5001, 0.3959, 0.5535],
        [0.1764, 0.8908, 0.6034, 0.8045],
        [0.7392, 0.7757, 0.7019, 0.6842]]) 
 tensor([0.9988, 0.1284, 0.0111, 0.6083])
tensor([[1.7364, 0.6285, 0.4069, 1.1618],
        [1.1752, 1.0192, 0.6145, 1.4128],
        [1.7381, 0.9041, 0.7130, 1.2925]])
tensor([[1.7364, 0.6285, 0.4069, 1.1618],
        [1.1752, 1.0192, 0.6145, 1.4128],
        [1.7381, 0.9041, 0.7130, 1.2925]])


In [15]:
# sub 减；mul 乘；div 除
print(torch.sub(a,b))
print(torch.mul(a,b))
print(torch.div(a,b))


tensor([[-0.2613,  0.3717,  0.3848, -0.0547],
        [-0.8225,  0.7624,  0.5923,  0.1963],
        [-0.2596,  0.6473,  0.6909,  0.0759]])
tensor([[0.7367, 0.0642, 0.0044, 0.3367],
        [0.1762, 0.1144, 0.0067, 0.4894],
        [0.7384, 0.0996, 0.0078, 0.4162]])
tensor([[ 0.7384,  3.8940, 35.7988,  0.9100],
        [ 0.1766,  6.9363, 54.5637,  1.3227],
        [ 0.7401,  6.0399, 63.4725,  1.1249]])


In [16]:
torch.eq(a-b, torch.sub(a,b))
torch.all(torch.eq(a-b, torch.sub(a,b)))

tensor(True)

In [17]:
# 矩阵相乘 matmul --- 另一种写法：@
a = torch.rand(1,4)
b = torch.rand(4,1)
print(torch.matmul(a,b))
print(a@b)


tensor([[0.2245]])
tensor([[0.2245]])


In [18]:
# Power exp log
# sqrt ,rsqrt
a = torch.full([2,3],3)
print(a.pow(2))
print(a**2)

tensor([[9, 9, 9],
        [9, 9, 9]])
tensor([[9, 9, 9],
        [9, 9, 9]])


# 统计性质
norm----范数        
mean_sum    
prod----所有元素的积    
max, min, argmin, argmax    
kthvalue, topk

In [19]:
a = torch.arange(8).view(2,4).type(torch.FloatTensor)
print(a)
print(a.min(), a.max(), a.mean(), a.prod())

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]], dtype=torch.float32)
tensor(0., dtype=torch.float32) tensor(7., dtype=torch.float32) tensor(3.5000, dtype=torch.float32) tensor(0., dtype=torch.float32)


In [20]:
# 类中__call__的使用
class test():
    def __init__(self, a):
        print(a)
        pass
    def __call__(self, b):
        print(b)
        pass
c = test(1111)
c(111111111)

1111
111111111


# where 和 gather操作

In [21]:
# where
# torch.where(condition, x, y)
cond = torch.rand(2,2)
print(cond)
a = torch.ones(2,2)
b = torch.zeros(2,2)
torch.where(cond>0.5, a, b)

tensor([[0.8965, 0.8287],
        [0.8277, 0.9551]])


tensor([[1., 1.],
        [1., 1.]])

In [22]:
# gather搜集
# torch.gather(input, dim, index, out=None)
a = torch.arange(10)+100
print(a)
torch.gather(a.expand(4,10), dim=1, index=torch.tensor([[1,1,2],[1,2,3],[1,4,3],[0,5,3]]))

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])


tensor([[101, 101, 102],
        [101, 102, 103],
        [101, 104, 103],
        [100, 105, 103]])

# PyTorch 自动求导
1、创建求导变量，在创建张量时 requires_grad=True    
2、使用 backward() 求出导数（梯度）或者使用 autograd.grad() 求出导数（梯度）

In [65]:
from torch.nn import functional as F
x = torch.ones(1)
# w = torch.full([1],5., requires_grad=True)
w = torch.full([1],5.)
w.requires_grad_()
mse = F.mse_loss(torch.ones(1), x*w)

# 使用 autograd.grad() 求导
# 使用 retain_graph 可保留图（每次求导，图被清除，必须再次建立，使用retain_graph可保留图到下次求导）
a = torch.autograd.grad(mse, [w], retain_graph=True)
print(a)

# 使用 backward() 求导
mse.backward()
print(w.grad)


(tensor([8.]),)
tensor([8.])
