In [2]:
# 导入包
import torch
import numpy as np

# 1、数据类型
    int                     IntTensor
    float                   FloatTensor
    int array               IntTensor[d1,d2,...]
    float array             FloatTensor[d1,d2,...]
    string                  使用编码的方式表示string类型

# from_numpy()
使用 from_numpy() 将 numpy 数据转化为 tensor    
默认为torch.float64类型 torch.DoubleTensor

In [8]:
# import from numpy
a = np.array([2,3.4])
a = torch.from_numpy(a)
print(a)
b = np.ones([2,3])
b = torch.from_numpy(b)
print(b)

tensor([2.0000, 3.4000], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [15]:
# import from list
a = torch.tensor([2., 3.2])
print(a, a.type())
b = torch.tensor([[2,3.2], [1,2.2]])
print(b, b.type())

tensor([2.0000, 3.2000]) torch.FloatTensor
tensor([[2.0000, 3.2000],
        [1.0000, 2.2000]]) torch.FloatTensor


# empty, Tensor, IntTensor, FloatTensor的应用
torch.Tensor()是python类-----------torch.FloatTensor    
torch.tensor()是python函数  
Tensor()接收维度， tensor()接收数据     
效果差不多，用法有一定的区别

In [26]:
# 初始化数据的函数
a = torch.empty(1,4)
print(a, a.type()) 
b = torch.Tensor(2,3)   # 随机
print(b, b.type())
c = torch.tensor((1,2,3))
print(c, c.type())

tensor([[0., 0., 0., 0.]]) torch.FloatTensor
tensor([[0.0000e+00, 3.2485e-05, 1.8754e+28],
        [2.5991e-06, 2.6542e+20, 1.2801e-11]]) torch.FloatTensor
tensor([1, 2, 3]) torch.LongTensor


# 改变默认数据类型 
PyTorch的默认类型是FloatTensor  
使用set_default_tensor_type()改变默认数据类型

In [34]:
print(torch.tensor([1.2, 3]).type())
torch.set_default_tensor_type(torch.DoubleTensor)
print(torch.tensor([1.2, 3]).type())

torch.FloatTensor
torch.DoubleTensor


# 切片

In [43]:
a = torch.rand(4,5,6)
print(a.shape)
b = a[0:3:2,:,:]
print(b.shape)
print(a[a>0.5])

torch.Size([4, 5, 6])
torch.Size([2, 5, 6])
tensor([0.9733, 0.9707, 0.7172, 0.9166, 0.7538, 0.5561, 0.5444, 0.7687, 0.6960,
        0.6438, 0.8167, 0.6491, 0.6019, 0.6291, 0.8216, 0.7978, 0.6504, 0.5091,
        0.6076, 0.8951, 0.9662, 0.5174, 0.6050, 0.5692, 0.5277, 0.8755, 0.5629,
        0.7718, 0.5054, 0.9238, 0.6854, 0.8229, 0.8274, 0.7297, 0.9521, 0.9316,
        0.8941, 0.7441, 0.9983, 0.6757, 0.8762, 0.8135, 0.8362, 0.5358, 0.6966,
        0.7780, 0.5041, 0.7573, 0.8026, 0.7857, 0.8523, 0.7048])


# 维度变换

In [45]:
# 使用view变换维度
a = torch.rand(4,3,2)
print(a)

b = a.view(4, 3*2)
print(b)

tensor([[[5.5668e-01, 9.7550e-01],
         [3.5943e-01, 5.7385e-01],
         [9.2970e-01, 1.6190e-01]],

        [[5.5118e-03, 5.4063e-03],
         [2.3668e-01, 8.7479e-01],
         [5.7701e-01, 3.7321e-01]],

        [[8.1164e-01, 1.6432e-01],
         [7.4977e-01, 2.8836e-01],
         [8.2767e-01, 7.4640e-01]],

        [[3.1480e-01, 6.1099e-01],
         [2.5750e-01, 8.8531e-01],
         [1.0503e-04, 4.7937e-01]]])
tensor([[5.5668e-01, 9.7550e-01, 3.5943e-01, 5.7385e-01, 9.2970e-01, 1.6190e-01],
        [5.5118e-03, 5.4063e-03, 2.3668e-01, 8.7479e-01, 5.7701e-01, 3.7321e-01],
        [8.1164e-01, 1.6432e-01, 7.4977e-01, 2.8836e-01, 8.2767e-01, 7.4640e-01],
        [3.1480e-01, 6.1099e-01, 2.5750e-01, 8.8531e-01, 1.0503e-04, 4.7937e-01]])


In [52]:
# 使用 unsqueeze 增维
# unsqueeze(x) 再x位置上插入一个维度
print(a.unsqueeze(0).shape)
print(a.unsqueeze(1).shape)
print(a.unsqueeze(-1).shape)
print(a.unsqueeze(-2).shape)

torch.Size([1, 4, 3, 2])
torch.Size([4, 1, 3, 2])
torch.Size([4, 3, 2, 1])
torch.Size([4, 3, 1, 2])


In [59]:
# 使用 unsqueeze 降维(不包含参数的维度)
a = torch.rand(4,3,1,1)
print(a.squeeze(0).shape)
print(a.squeeze(1).shape)
print(a.squeeze(2).shape)
print(a.squeeze(3).shape)
print(a.squeeze(2).squeeze(2).shape)


torch.Size([4, 3, 1, 1])
torch.Size([4, 3, 1, 1])
torch.Size([4, 3, 1])
torch.Size([4, 3, 1])
torch.Size([4, 3])


In [74]:
# 使用 expand 扩展维度(扩张维度为1的位置)
a = torch.rand(4,2,1)
print(a)
print(a.expand(4,2,2))

tensor([[[0.8612],
         [0.3787]],

        [[0.6890],
         [0.7986]],

        [[0.1182],
         [0.4506]],

        [[0.0793],
         [0.5988]]])
tensor([[[0.8612, 0.8612],
         [0.3787, 0.3787]],

        [[0.6890, 0.6890],
         [0.7986, 0.7986]],

        [[0.1182, 0.1182],
         [0.4506, 0.4506]],

        [[0.0793, 0.0793],
         [0.5988, 0.5988]]])


In [78]:
# 使用 repeat 扩展维度
a = torch.rand(2,1)
print(a)
print(a.repeat(2,2))
print(a.repeat(2*2,2))

tensor([[0.0443],
        [0.1001]])
tensor([[0.0443, 0.0443],
        [0.1001, 0.1001],
        [0.0443, 0.0443],
        [0.1001, 0.1001]])
tensor([[0.0443, 0.0443],
        [0.1001, 0.1001],
        [0.0443, 0.0443],
        [0.1001, 0.1001],
        [0.0443, 0.0443],
        [0.1001, 0.1001],
        [0.0443, 0.0443],
        [0.1001, 0.1001]])


# 拼接与拆分 --- Cat, Stack, Split, Chunk

In [115]:
a = torch.rand(2,2)
b = torch.rand(2,2)
print(a, b)
print(torch.cat([a, b], dim=1).shape)
print(torch.cat([a, b], dim=0).shape)
print(torch.stack([a, b], dim=0).shape)
print(torch.stack([a, b], dim=1).shape)
print(a.split(1, dim=1))
print(a.chunk(2, dim=0))    # 等量分割

tensor([[0.8095, 0.2212],
        [0.0009, 0.1118]]) tensor([[0.9768, 0.9019],
        [0.8844, 0.3871]])
torch.Size([2, 4])
torch.Size([4, 2])
torch.Size([2, 2, 2])
torch.Size([2, 2, 2])
(tensor([[0.8095],
        [0.0009]]), tensor([[0.2212],
        [0.1118]]))
(tensor([[0.8095, 0.2212]]), tensor([[0.0009, 0.1118]]))


# PyTorch 的基本数学运算
## 数学运算
Add/minus/multiply/divide   
Matmul  
Pow     
Sqrt/rsqrt  
Round


In [121]:
# add 加
a = torch.rand(3,4)
b = torch.rand(4)
print(a, "\n", b)
print(a+b)
print(torch.add(a,b))

tensor([[0.9633, 0.9761, 0.4742, 0.3007],
        [0.4219, 0.1869, 0.9068, 0.9499],
        [0.1363, 0.8625, 0.9305, 0.6567]]) 
 tensor([0.0362, 0.5049, 0.1859, 0.2974])
tensor([[0.9995, 1.4811, 0.6600, 0.5981],
        [0.4581, 0.6919, 1.0927, 1.2474],
        [0.1725, 1.3674, 1.1164, 0.9541]])
tensor([[0.9995, 1.4811, 0.6600, 0.5981],
        [0.4581, 0.6919, 1.0927, 1.2474],
        [0.1725, 1.3674, 1.1164, 0.9541]])


In [122]:
# sub 减；mul 乘；div 除
print(torch.sub(a,b))
print(torch.mul(a,b))
print(torch.div(a,b))


tensor([[ 0.9271,  0.4712,  0.2883,  0.0032],
        [ 0.3857, -0.3180,  0.7210,  0.6525],
        [ 0.1001,  0.3575,  0.7447,  0.3592]])
tensor([[0.0349, 0.4929, 0.0881, 0.0894],
        [0.0153, 0.0944, 0.1685, 0.2826],
        [0.0049, 0.4355, 0.1729, 0.1953]])
tensor([[26.6175,  1.9331,  2.5512,  1.0108],
        [11.6578,  0.3702,  4.8791,  3.1936],
        [ 3.7665,  1.7081,  5.0067,  2.2076]])


In [129]:
torch.eq(a-b, torch.sub(a,b))
torch.all(torch.eq(a-b, torch.sub(a,b)))

tensor(True)

In [133]:
# 矩阵相乘 matmul --- 另一种写法：@
a = torch.rand(1,4)
b = torch.rand(4,1)
print(torch.matmul(a,b))
print(a@b)


tensor([[1.0444]])
tensor([[1.0444]])


In [136]:
# Power exp log
# sqrt ,rsqrt
a = torch.full([2,3],3)
print(a.pow(2))
print(a**2)

tensor([[9, 9, 9],
        [9, 9, 9]])
tensor([[9, 9, 9],
        [9, 9, 9]])


# 统计性质