# GAN
第1步——向鉴别器展示一个真实的数据样本，告诉它该样本的分类应该是1.0。    
第2步——向鉴别器显示一个生成器的输出，告诉它该样本的分类应该是0.0。  
第3步——向鉴别器显示一个生成器的输出，告诉生成器结果应该是1.0。  

In [7]:
import torch
import torch.nn as nn
import pandas
import matplotlib.pyplot as plt
import numpy as np

# torch.nn
torch.nn是一个非常重要的模块，是pytorch神经网络模块化的核心。这个模块定义了一些列模块，包括卷积层nn.ConvNd(N=1,2,3)和线性层（全连接层）nn.linear等。另外，torch.nn中也定义了一些列的损失函数。

In [23]:
np.random.seed(10)
dtype = torch.FloatTensor
def generate_real():
    real_data = torch.FloatTensor(
            [np.random.uniform(0.8, 1.0),
            np.random.uniform(0.0, 0.2),
            np.random.uniform(0.8, 1.0),
            np.random.uniform(0.0, 0.2)])     # CPU上32位浮点型
    return real_data


# parameters()
其中放入了可以优化的参数---权重和偏置量

In [63]:
model = nn.Sequential(nn.Linear(1, 1).type(dtype),
                        nn.Linear(1, 2).type(dtype))
# model1=nn.Linear(1, 1).type(dtype)
# model2=nn.Linear(1, 1).type(dtype)
# 方法一
# for i in model.parameters():
#     print(i)

# 方法二
# for i in model.named_parameters():
#     print(i)

#方法三
# for i in model.state_dict():
#     print(i)

a = list(model.parameters())
b = list(model.named_parameters())
c = model.state_dict()
print(b)


[('0.weight', Parameter containing:
tensor([[-0.8194]], requires_grad=True)), ('0.bias', Parameter containing:
tensor([0.5863], requires_grad=True)), ('1.weight', Parameter containing:
tensor([[ 0.9539],
        [-0.5931]], requires_grad=True)), ('1.bias', Parameter containing:
tensor([0.9821, 0.6215], requires_grad=True))]


In [47]:
print((model(torch.tensor([0]).type(dtype))))

tensor([ 0.3021, -0.9483], grad_fn=<AddBackward0>)
